[secrets]
  # Kertoo tietoturvaskannerille, että nämä ympäristömuuttujat on tarkoituksella
  # jätettävä huomiotta, koska ne ovat julkisia Firebase-yhteyttä varten.
  scan_omit_keys = [
    "VITE_FIREBASE_API_KEY",
    "VITE_FIREBASE_AUTH_DOMAIN",
    "VITE_FIREBASE_PROJECT_ID",
    "VITE_FIREBASE_STORAGE_BUCKET",
    "VITE_FIREBASE_MESSAGING_SENDER_ID",
    "VITE_FIREBASE_APP_ID"
  ]